"""Engine-default UI strings (Fase 1.2, extended in Fase 1.6).

Base ES/EN copy for the WOW editorial template, shared by every vertical.
Per-vertical `strings_overrides` (from `verticals/<id>/vertical.yaml`) are
layered on top of this in `vertical_config.py` — see `build_strings()`.
Values marked *_html may contain trusted inline markup (<em>) and are
injected without re-escaping.

Fase 1.6 re-sync with HMU Link HEAD adds: `skip_to_content` (a11y skip link),
`price_ask` ("Consultar"/"Ask us" legend for price-less services),
`class_schedule_title`/`tour_details_title`/`pet_notes_title` (extra info-row
sections), `footer_privacy` (minimal legal footer link) and localizes the ES
`delivery_pickup_label` to "Entrega / recoger".

Fase 3.2 adds `lookbook_eyebrow`/`lookbook_title_html` for the optional
mini-lookbook block (ported from ModaLink, see blocks.py).
"""

from __future__ import annotations

BASE_STRINGS = {
    "es": {
        "title_suffix": "Servicios",
        "btn_whatsapp": "Reservar por WhatsApp",
        "btn_phone": "Llamar",
        "btn_email": "Enviar correo",
        "btn_website": "Sitio web",
        "btn_booking": "Reservar en linea",
        "btn_maps": "Google Maps",
        "btn_other": "Abrir enlace",
        "gallery_prev": "Foto anterior",
        "gallery_next": "Foto siguiente",
        "gallery_photo": "Foto",
        "lookbook_eyebrow": "Galería",
        "lookbook_title_html": "Mini <em>lookbook</em>",
        "delivery_pickup_label": "Entrega / recoger",
        "portfolio_label": "Portafolio",
        "view_menu": "Ver servicios",
        "scroll_hint": "Desliza",
        "skip_to_content": "Saltar al contenido",
        "services_eyebrow": "Servicios",
        "menu_title_html": "Nuestros <em>servicios</em>",
        "services_fallback": "Servicios",
        "price_ask": "Consultar",
        "featured_badge": "Destacado",
        "visit_eyebrow": "Detalles",
        "visit_title_html": "Planea tu <em>visita</em>",
        "hours_title": "Horarios",
        "client_care_title": "Atencion",
        "reservations_title": "Reservaciones",
        "address_title": "Dónde estamos",
        "address_map": "Ver en Google Maps",
        "location_label": "Ubicacion",
        "service_area_title": "Area de servicio",
        "class_schedule_title": "Horario de clases",
        "tour_details_title": "Sobre la experiencia",
        "pet_notes_title": "Antes de tu visita",
        "policies_title": "Políticas",
        "links_title": "Enlaces",
        "faq_eyebrow": "FAQ",
        "faq_title_html": "Preguntas <em>frecuentes</em>",
        "share_eyebrow": "Comparte",
        "share_title_html": "Llévanos <em>contigo</em>",
        "share_lead": "Escanea el código o comparte el link directo.",
        "share_button": "Compartir link",
        "share_copied": "Link copiado",
        "footer_credit": "Hecho con {brand_name}",
        "footer_privacy": "Privacidad",
        "footer_demo_credit": "Demo hecho con {brand_name}",
        "qr_alt": "Codigo QR de",
        "lang_switch": "View this page in English",
    },
    "en": {
        "title_suffix": "Services",
        "btn_whatsapp": "Book on WhatsApp",
        "btn_phone": "Call",
        "btn_email": "Send an email",
        "btn_website": "Website",
        "btn_booking": "Book online",
        "btn_maps": "Google Maps",
        "btn_other": "Open link",
        "gallery_prev": "Previous photo",
        "gallery_next": "Next photo",
        "gallery_photo": "Photo",
        "lookbook_eyebrow": "Gallery",
        "lookbook_title_html": "Mini <em>lookbook</em>",
        "delivery_pickup_label": "Delivery / pickup",
        "portfolio_label": "Portfolio",
        "view_menu": "See services",
        "scroll_hint": "Scroll",
        "skip_to_content": "Skip to content",
        "services_eyebrow": "Services",
        "menu_title_html": "Our <em>services</em>",
        "services_fallback": "Services",
        "price_ask": "Ask us",
        "featured_badge": "Featured",
        "visit_eyebrow": "Details",
        "visit_title_html": "Plan your <em>visit</em>",
        "hours_title": "Hours",
        "client_care_title": "How we work",
        "reservations_title": "Reservations",
        "address_title": "Where we are",
        "address_map": "View on Google Maps",
        "location_label": "Location",
        "service_area_title": "Service area",
        "class_schedule_title": "Class schedule",
        "tour_details_title": "About the experience",
        "pet_notes_title": "Before your visit",
        "policies_title": "Policies",
        "links_title": "Links",
        "faq_eyebrow": "FAQ",
        "faq_title_html": "Common <em>questions</em>",
        "share_eyebrow": "Share",
        "share_title_html": "Take us <em>with you</em>",
        "share_lead": "Scan the code or share the direct link.",
        "share_button": "Share link",
        "share_copied": "Link copied",
        "footer_credit": "Made with {brand_name}",
        "footer_privacy": "Privacy",
        "footer_demo_credit": "Demo made with {brand_name}",
        "qr_alt": "QR code for",
        "lang_switch": "Ver esta página en español",
    },
}
